CREATE TABLE PARTICIPANTES (
  id_PARTICIPANTES INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(255) NULL,
  TELEFONE INTEGER UNSIGNED NULL,
  EMAIL VARCHAR(45) NULL,
  PRIMARY KEY(id_PARTICIPANTES)
);

CREATE TABLE ENDERECO (
  id_ENDERECO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NUMERO INTEGER UNSIGNED NULL,
  COMPLEMENTO VARCHAR(45) NULL,
  BAIRRO VARCHAR(45) NULL,
  CIDADE VARCHAR(45) NULL,
  ESTADO VARCHAR(45) NULL,
  PAIS VARCHAR(45) NULL,
  RUA VARCHAR(255) NULL,
  PRIMARY KEY(id_ENDERECO)
);

CREATE TABLE ATIVIDADE (
  id_ATIVIDADE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ENDERECO_id_ENDERECO INTEGER UNSIGNED NOT NULL,
  TITULO VARCHAR(20) NULL,
  DATA_2 DATE NULL,
  HORA TIME NULL,
  PERIODICIDADE VARCHAR(20) NULL,
  PRIMARY KEY(id_ATIVIDADE, ENDERECO_id_ENDERECO),
  INDEX ATIVIDADE_FKIndex1(ENDERECO_id_ENDERECO)
);

CREATE TABLE ATIVIDADE_has_PARTICIPANTES (
  ATIVIDADE_ENDERECO_id_ENDERECO INTEGER UNSIGNED NOT NULL,
  ATIVIDADE_id_ATIVIDADE INTEGER UNSIGNED NOT NULL,
  PARTICIPANTES_id_PARTICIPANTES INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ATIVIDADE_ENDERECO_id_ENDERECO, ATIVIDADE_id_ATIVIDADE, PARTICIPANTES_id_PARTICIPANTES),
  INDEX ATIVIDADE_has_PARTICIPANTES_FKIndex1(ATIVIDADE_id_ATIVIDADE, ATIVIDADE_ENDERECO_id_ENDERECO),
  INDEX ATIVIDADE_has_PARTICIPANTES_FKIndex2(PARTICIPANTES_id_PARTICIPANTES)
);

